package com.tikuzhushou.audit;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.tikuzhushou.config.TraceFilter;
import jakarta.servlet.http.HttpServletRequest;
import java.sql.Timestamp;
import java.time.*;
import java.util.*;
import org.slf4j.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;
import org.springframework.web.context.request.*;

/** Append-only, redacted semantic audit events for the administrator center. */
@Service
public class AdminAuditService {
  private static final Logger log=LoggerFactory.getLogger(AdminAuditService.class); private static final ObjectMapper JSON=new ObjectMapper(); private static final int DAYS=30;
  public static final String KB_CREATE="KB_CREATE",KB_UPDATE="KB_UPDATE",KB_ARCHIVE="KB_ARCHIVE",KB_QUOTA_UPDATE="KB_QUOTA_UPDATE",DOCUMENT_UPLOAD="DOCUMENT_UPLOAD",DOCUMENT_PARSE_SUBMIT="DOCUMENT_PARSE_SUBMIT",DOCUMENT_PAGE_EDIT="DOCUMENT_PAGE_EDIT",DOCUMENT_TABLE_EDIT="DOCUMENT_TABLE_EDIT",DOCUMENT_CHUNK_EDIT="DOCUMENT_CHUNK_EDIT",STANDARD_EXTRACT_SUBMIT="STANDARD_EXTRACT_SUBMIT",STANDARD_CONFIRM="STANDARD_CONFIRM",STANDARD_UPDATE="STANDARD_UPDATE",BLUEPRINT_CREATE="BLUEPRINT_CREATE",BLUEPRINT_UPDATE="BLUEPRINT_UPDATE",QUESTIONS_SUBMIT="QUESTIONS_SUBMIT",GENERATION_RETRY="GENERATION_RETRY",GENERATION_CANCEL="GENERATION_CANCEL",EXPORT_SUBMIT="EXPORT_SUBMIT",EXPORT_DOWNLOAD="EXPORT_DOWNLOAD",REVIEW_UPDATE="REVIEW_UPDATE",EXCEL_VALIDATE="EXCEL_VALIDATE",EXCEL_IMPORT="EXCEL_IMPORT",ASSISTANT_CONVERSATION_CREATE="ASSISTANT_CONVERSATION_CREATE",ASSISTANT_CONVERSATION_DELETE="ASSISTANT_CONVERSATION_DELETE",WORKFLOW_TASK_CANCEL="WORKFLOW_TASK_CANCEL",USER_CREATE="USER_CREATE",USER_UPDATE="USER_UPDATE",MODEL_CONFIG_UPDATE="MODEL_CONFIG_UPDATE",LOGIN_SUCCESS="LOGIN_SUCCESS",LOGIN_FAILURE="LOGIN_FAILURE",LOGIN_EMAIL_CODE="LOGIN_EMAIL_CODE",LOGOUT="LOGOUT",EMAIL_CODE_REQUEST="EMAIL_CODE_REQUEST";
  public static final String TARGET_KB="KNOWLEDGE_BASE",TARGET_DOCUMENT="DOCUMENT",TARGET_STANDARD="STANDARD",TARGET_BLUEPRINT="BLUEPRINT",TARGET_JOB="GENERATION_JOB",TARGET_TASK="WORKFLOW_TASK",TARGET_ARTIFACT="EXPORT_ARTIFACT",TARGET_REVIEW="REVIEW",TARGET_USER="USER",TARGET_MODEL_CONFIG="MODEL_CONFIG",TARGET_ASSISTANT="ASSISTANT_CONVERSATION",TARGET_EXCEL="EXCEL",TARGET_AUTH="AUTHENTICATION";
  private final JdbcTemplate jdbc; public AdminAuditService(JdbcTemplate jdbc){this.jdbc=jdbc;}
  public String currentActor(){return Optional.ofNullable(SecurityContextHolder.getContext().getAuthentication()).map(a->a.getName()).orElse("system");}
  public void record(String action,String target,UUID id,String name,Map<String,Object> detail){record(action,target,id,name,detail,currentActor(),"SUCCESS");}
  public void record(String action,String target,UUID id,String name,Map<String,Object> detail,String actor){record(action,target,id,name,detail,actor,"SUCCESS");}
  public void recordSecurity(String action,String actor,String outcome,Map<String,Object> detail){record(action,TARGET_AUTH,null,null,detail,actor,outcome);}
  public void record(String action,String target,UUID id,String name,Map<String,Object> detail,String actor,String outcome){try{ServletRequestAttributes a=(ServletRequestAttributes)RequestContextHolder.getRequestAttributes();HttpServletRequest r=a==null?null:a.getRequest();String safeActor=Objects.requireNonNullElse(actor,"system");jdbc.update("insert into admin_operation_log(id,actor_id,actor_name,action,target_type,target_id,target_name,detail,http_method,path,status,request_id,category,outcome,risk_level,created_at) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",UUID.randomUUID(),userId(safeActor),safeActor,action,target,id,name,toJson(sanitize(detail)),r==null?null:r.getMethod(),r==null?null:r.getRequestURI(),"SUCCESS".equals(outcome)?200:500,MDC.get(TraceFilter.MDC_KEY),category(action),outcome,risk(action,outcome),Timestamp.from(Instant.now()));}catch(Exception e){log.error("AUDIT_PERSIST_FAILED action={} target={}",action,target,e);}}
  public Map<String,Object> page(int limit,int offset,String action,String actor,String target,String outcome,String risk,String from,String to){Instant[] w=window(from,to);StringBuilder q=new StringBuilder(" where created_at>=? and created_at<?");List<Object> p=new ArrayList<>(List.of(Timestamp.from(w[0]),Timestamp.from(w[1])));filter(q,p,"action",action);filter(q,p,"actor_name",actor,false);filter(q,p,"target_type",target);filter(q,p,"outcome",outcome);filter(q,p,"risk_level",risk);int size=Math.max(1,Math.min(limit,100)),skip=Math.max(0,offset);Integer total=jdbc.queryForObject("select count(*) from admin_operation_log"+q,Integer.class,p.toArray());List<Object> rowArgs=new ArrayList<>(p);rowArgs.add(size);rowArgs.add(skip);List<Map<String,Object>> items=jdbc.query("select id,actor_name,action,target_type,target_id,target_name,detail,http_method,path,status,request_id,category,outcome,risk_level,created_at from admin_operation_log"+q+" order by created_at desc,id desc limit ? offset ?",(rs,n)->map(rs),rowArgs.toArray());return Map.of("items",items,"total",total==null?0:total,"limit",size,"offset",skip,"hasMore",skip+items.size()<(total==null?0:total));}
  public Map<String,Object> summary(String from,String to){Instant[] w=window(from,to);Timestamp b=Timestamp.from(w[0]),e=Timestamp.from(w[1]);return Map.of("total",count("select count(*) from admin_operation_log where created_at>=? and created_at<?",b,e),"failed",count("select count(*) from admin_operation_log where created_at>=? and created_at<? and outcome<>'SUCCESS'",b,e),"highRisk",count("select count(*) from admin_operation_log where created_at>=? and created_at<? and risk_level in ('HIGH','CRITICAL')",b,e),"security",count("select count(*) from admin_operation_log where created_at>=? and created_at<? and category='SECURITY'",b,e));}
  public List<Map<String,Object>> list(int limit,String action,String actor,String target){@SuppressWarnings("unchecked") List<Map<String,Object>> rows=(List<Map<String,Object>>)page(limit,0,action,actor,target,null,null,null,null).get("items");return rows;}
  @Scheduled(cron="0 10 3 * * *") public void retainThirtyDays(){int removed=jdbc.update("delete from admin_operation_log where created_at<?",Timestamp.from(Instant.now().minusSeconds(DAYS*86400L)));log.info("admin audit retention removed {} rows",removed);}
  private UUID userId(String actor){try{return jdbc.query("select id from app_users where username=?",(rs,n)->UUID.fromString(rs.getString(1)),actor).stream().findFirst().orElse(null);}catch(Exception ignored){return null;}}
  private Map<String,Object> map(java.sql.ResultSet rs)throws java.sql.SQLException{Map<String,Object> row=new LinkedHashMap<>();row.put("id",rs.getString("id"));row.put("actor",rs.getString("actor_name"));row.put("action",rs.getString("action"));row.put("targetType",rs.getString("target_type"));row.put("targetId",Objects.toString(rs.getString("target_id"),""));row.put("targetName",Objects.toString(rs.getString("target_name"),""));row.put("detail",Objects.toString(rs.getString("detail"),""));row.put("method",Objects.toString(rs.getString("http_method"),""));row.put("path",Objects.toString(rs.getString("path"),""));row.put("status",rs.getInt("status"));row.put("requestId",Objects.toString(rs.getString("request_id"),""));row.put("category",rs.getString("category"));row.put("outcome",rs.getString("outcome"));row.put("riskLevel",rs.getString("risk_level"));row.put("createdAt",rs.getTimestamp("created_at").toInstant());return row;}
  private Integer count(String sql,Object...args){Integer n=jdbc.queryForObject(sql,Integer.class,args);return n==null?0:n;} private void filter(StringBuilder q,List<Object> p,String col,String v){filter(q,p,col,v,true);}private void filter(StringBuilder q,List<Object> p,String col,String v,boolean upper){if(v!=null&&!v.isBlank()){q.append(" and ").append(col).append("=?");p.add(upper?v.trim().toUpperCase(Locale.ROOT):v.trim());}}
  private Instant[] window(String from,String to){LocalDate now=LocalDate.now(),min=now.minusDays(DAYS-1),b=date(from,now.minusDays(6)),e=date(to,now);if(b.isBefore(min))b=min;if(e.isBefore(b))e=b;ZoneId z=ZoneId.systemDefault();return new Instant[]{b.atStartOfDay(z).toInstant(),e.plusDays(1).atStartOfDay(z).toInstant()};}private LocalDate date(String s,LocalDate d){try{return s==null||s.isBlank()?d:LocalDate.parse(s);}catch(Exception ignored){return d;}}
  private String category(String a){if(a.startsWith("LOGIN")||a.equals(LOGOUT)||a.equals(EMAIL_CODE_REQUEST))return "SECURITY";if(a.startsWith("USER")||a.startsWith("MODEL"))return "ADMIN";if(a.startsWith("DOCUMENT")||a.startsWith("KB"))return "KNOWLEDGE";if(a.startsWith("STANDARD"))return "STANDARD";if(a.startsWith("BLUEPRINT")||a.startsWith("QUESTIONS")||a.startsWith("GENERATION")||a.startsWith("REVIEW"))return "GENERATION";return "BUSINESS";}private String risk(String a,String o){if(!"SUCCESS".equals(o))return "HIGH";if(a.equals(MODEL_CONFIG_UPDATE)||a.equals(USER_UPDATE))return "HIGH";if(a.startsWith("EXPORT")||a.startsWith("LOGIN"))return "MEDIUM";return "NORMAL";}
  private Object sanitize(Object v){if(v instanceof Map<?,?> m){Map<String,Object> out=new LinkedHashMap<>();m.forEach((k,x)->{String key=String.valueOf(k),low=key.toLowerCase(Locale.ROOT);out.put(key,low.matches(".*(password|secret|token|api.?key|authorization|cookie|code).*")?"[已脱敏]":sanitize(x));});return out;}if(v instanceof Collection<?> c)return c.stream().limit(50).map(this::sanitize).toList();if(v instanceof CharSequence s)return s.length()>1000?s.subSequence(0,1000)+"…[已截断]":s.toString();return v;}private String toJson(Object d){if(d==null)return null;try{return JSON.writeValueAsString(d);}catch(Exception e){return "{\"summary\":\"审计详情序列化失败\"}";}}
}
